server:
  port: 6666
spring:
  application:
    name: qos-analyzer
  dataSource:
    jdbcUrl: jdbc:postgresql://localhost:7777/qos
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: qos
        show_sql: true
        use_sql_comments: true
        format_sql: true